AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '.circleci/**/*'
    - 'app/assets/bower_components/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout:
  Enabled: false

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['#[^\{\n]+$'] # ignore end of line comments
  Exclude:
    - 'Guardfile'

Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/NumericPredicate:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
